# Generated by Django 5.2.4 on 2025-08-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_order_trade_wallettransaction_charge_lasttradedprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balances',
            new_name='Balance',
        ),
    ]
