# Generated by Django 5.2.4 on 2025-08-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_balances_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name_plural': 'Balance'},
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name_plural': 'Charge'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='lasttradedprice',
            options={'verbose_name_plural': 'LTP'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name_plural': 'Trade'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name_plural': 'Wallet Transaction'},
        ),
    ]
